# Generated by Django 2.1.1 on 2018-09-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('father_name', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('citizenship_no', models.CharField(max_length=20)),
                ('issue_date', models.DateField()),
                ('issue_district', models.CharField(max_length=25)),
            ],
        ),
    ]
